### ISSUE TITLE
Sorry for opening an issue...

### ISSUE THREAD

**Issue by ghost** [JordanLozinski/valorant_keyfarm#1]
I am opening this issue to see if there was any way that you could help me set this up..

Thanks.

**Comment by jordan-zilch** [comment]
Sure I can. What operating system are you using?

**Comment by ghost** [comment]
> 
> 
> Sure I can. What operating system are you using?

I am using windows 10, would it be easier to run it on Linux (I can do a VPS?)

Or is windows fine

**Comment by jordan-zilch** [comment]
Windows 10 should be fine. On Windows the script can't end the browser process when the stream ends, so I think as the script runs there will be more and more stream tabs open on your browser. Once a day or so you should go and close the old tabs, because there's a good chance that once the stream goes down they'll raid somebody or host another stream or even start their stream back up and it'll use up your internet's bandwidth.

Do you have Python 3.7 or a higher version installed? Do you have a Twitch API client ID yet?

**Comment by ghost** [comment]
> 
> 
> Windows 10 should be fine. On Windows the script can't end the browser process when the stream ends, so I think as the script runs there will be more and more stream tabs open on your browser. Once a day or so you should go and close the old tabs, because there's a good chance that once the stream goes down they'll raid somebody or host another stream or even start their stream back up and it'll use up your internet's bandwidth.
> 
> Do you have Python 3.7 or a higher version installed? Do you have a Twitch API client ID yet?

I do have python 3.8.2, and I am unsure on how to do the "Twitch API client ID". I've tried and failed for about 30 minutes now...

**Comment by jordan-zilch** [comment]
Ok I can try to help.
[Go here](https://dev.twitch.tv/console/apps/create) and log into your Twitch account if you aren't already logged in.
It should look like this:
![Register your Application](https://i.imgur.com/3qqs8ld.png)

You can put whatever you want in "name". For "OAuth Redirect URLs" you can just put "http://localhost". For category you can just select Application Integration. (I'm pretty sure it doesn't matter what you pick.) Then you hit the create button and it'll give you a client id.

**Comment by ghost** [comment]
> 
> 
> Ok I can try to help.
> [Go here](https://dev.twitch.tv/console/apps/create) and log into your Twitch account if you aren't already logged in.
> It should look like this:
> ![Register your Application](https://camo.githubusercontent.com/75ce0bd646b073e951e995568876bb0fcdcbe62c/68747470733a2f2f692e696d6775722e636f6d2f33717173386c642e706e67)
> 
> You can put whatever you want in "name". For "OAuth Redirect URLs" you can just put "http://localhost". For category you can just select Application Integration. (I'm pretty sure it doesn't matter what you pick.) Then you hit the create button and it'll give you a client id.

okay, got it

**Comment by jordan-zilch** [comment]
Do you know how to run python from command line? Try `python valorant.py {CLIENT_ID}` in command line

**Comment by CaptinSparkles** [comment]
`C:\Users\Cameron Patch\Desktop\Valorant-watcher-1.0.3\Test\valorant_keyfarm-master>python valorant.py {mokj8jj3keiwxk1m1ukoaw4cfk4kti}
Traceback (most recent call last):
  File "valorant.py", line 56, in <module>
    main()
  File "valorant.py", line 29, in main
    for stream in helix.streams(game_id=516575):
  File "C:\Users\Cameron Patch\AppData\Roaming\Python\Python38\site-packages\twitch\helix\helix.py", line 59, in streams
    return helix.Streams(self.api, **kwargs)
  File "C:\Users\Cameron Patch\AppData\Roaming\Python\Python38\site-packages\twitch\helix\resources\streams.py", line 17, in __init__
    response: dict = self._api.get(self._path, params=kwargs)
  File "C:\Users\Cameron Patch\AppData\Roaming\Python\Python38\site-packages\twitch\api.py", line 111, in get
    return self.request('GET', path, ignore_cache, params=params, headers=self._headers(headers), **kwargs)
  File "C:\Users\Cameron Patch\AppData\Roaming\Python\Python38\site-packages\twitch\api.py", line 100, in request
    response.raise_for_status()
  File "C:\Users\Cameron Patch\AppData\Roaming\Python\Python38\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.twitch.tv/helix/streams?game_id=516575`

**Comment by CaptinSparkles** [comment]
![image](https://user-images.githubusercontent.com/8761513/79269076-79495d00-7e61-11ea-8af5-e50b073504b6.png)

**Comment by CaptinSparkles** [comment]
and or....

![image](https://user-images.githubusercontent.com/8761513/79269266-c6c5ca00-7e61-11ea-81db-3e52a383ede7.png)

**Comment by jordan-zilch** [comment]
The first error makes it seem like you didn't put in the client ID correctly. I get that error when I put in a random string for the client id. Make sure you didn't type it/copy paste it wrong somehow.

To fix the second error I think you can try `python valorant.py {CLIENT_ID} windows-default`.

**Comment by ghost** [comment]
> 
> 
> The first error makes it seem like you didn't put in the client ID correctly. I get that error when I put in a random string for the client id. Make sure you didn't type it/copy paste it wrong somehow.
> 
> To fix the second error I think you can try `python valorant.py {CLIENT_ID} windows-default`.

Oh wow, that was the fix. 

![image](https://user-images.githubusercontent.com/8761513/79270991-b2370100-7e64-11ea-8883-3ef1c4a2bea6.png)

**Comment by jordan-zilch** [comment]
I'm glad I could help! Let me know if you run into any other issues

**Comment by ghost** [comment]
> 
> 
> I'm glad I could help! Let me know if you run into any other issues

will do! I'll close the request now, thanks for all your help and sharing this program =)
